describe('test', () => {
    it('nopCommerce demo store. Register', () => {
      cy.viewport(1440, 900)
      cy.visit('https://demo.nopcommerce.com/')
      cy.get('.ico-register').click()
      cy.get('#gender-male').click()
      cy.get('#FirstName',).type('Joe')
      cy.get('#LastName',).type('Gibbard')
      cy.get('[name="DateOfBirthDay"]').select('2')
      cy.get('[name="DateOfBirthMonth"]').select('January')
      cy.get('[name="DateOfBirthYear"]').select('2000')
      cy.get('#Email').type('idyeyo41@gmail.com')
      cy.get('#Company').type('QA Engineer')
      cy.get('#Password').type('123456')
      cy.get('#ConfirmPassword').type('123456')
      cy.get('.page-body>form',).click()
      cy.get('#register-button',).click()
      cy.get('.result').click()
      cy.get('.result').should('include.text', 'Your registration completed')
    })
  })